- hosts: localhost
  vars_files:
    - host_vars/nectar.yml
  gather_facts: true

  roles: 
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    #- role: openstack-volume-snapshot
